[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
  "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/",
  "@openzeppelin/contracts-upgradeable/=node_modules/@openzeppelin/contracts-upgradeable/",
  "@pythnetwork/pyth-sdk-solidity/=node_modules/@pythnetwork/pyth-sdk-solidity/"
]

[rpc_endpoints]
robinhood_mainnet = "${ROBINHOOD_MAINNET_RPC}"
robinhood_testnet = "${ROBINHOOD_TESTNET_RPC}"

# See more config options https://github.com/foundry-rs/foundry/tree/master/crates/config
